# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'janela.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWIndow(object):
    def setupUi(self, MainWIndow):
        MainWIndow.setObjectName("MainWIndow")
        MainWIndow.resize(568, 458)
        MainWIndow.setStyleSheet("background-color: #323232;\n"
"border-radius:12px;\n"
"border:2px solid yellowgreen;\n"
"animation: 1.5s linear infinite;\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWIndow)
        self.centralwidget.setObjectName("centralwidget")
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(142, 100, 131, 41))
        self.loadButton.setStyleSheet("QPushButton{\n"
"width: 98%;\n"
"padding: 10px;\n"
"border-color:black;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-right-radius: 12px;\n"
"border:2px solid cyan;\n"
"background-color: #323232;\n"
"color: white;\n"
"font-family: \'Orbitron\', sans-serif;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: cyan;\n"
"    color:black;\n"
"}\n"
"")
        self.loadButton.setObjectName("loadButton")
        self.sendButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendButton.setGeometry(QtCore.QRect(302, 99, 141, 41))
        self.sendButton.setStyleSheet("QPushButton{\n"
"width: 98%;\n"
"padding: 10px;\n"
"border-color:black;\n"
"border-top-left-radius: 15px;\n"
"border-bottom-right-radius: 12px;\n"
"border:2px solid cyan;\n"
"background-color: #323232;\n"
"color: white;\n"
"font-family: \'Orbitron\', sans-serif;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: cyan;\n"
"    color:black;\n"
"}\n"
"")
        self.sendButton.setObjectName("sendButton")
        self.statusText = QtWidgets.QTextEdit(self.centralwidget)
        self.statusText.setGeometry(QtCore.QRect(70, 200, 451, 111))
        self.statusText.setObjectName("statusText")
        self.statusText.setStyleSheet("QTextEdit{"
"color: white;"
"background-color: rgb(0, 0, 0);"
"}")
        MainWIndow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWIndow)
        QtCore.QMetaObject.connectSlotsByName(MainWIndow)

    def retranslateUi(self, MainWIndow):
        _translate = QtCore.QCoreApplication.translate
        MainWIndow.setWindowTitle(_translate("MainWIndow", "LavAutomatic V.1.0"))
        self.loadButton.setText(_translate("MainWIndow", "Carregar Planilha"))
        self.sendButton.setText(_translate("MainWIndow", "Enviar Mensagens"))
